# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
# Copyright (c) Microsoft Corporation.  All Rights Reserved.
#
#
# Processor independent makefile

APPNAME=q3

all: $(APPNAME)

#--------------------------------------------------------------------#
# Build rules for the application.

$(APPNAME):
	@echo Building console application $(APPNAME)...
	@gcc main.c -o $(APPNAME)
	@echo ...done.
